name: Deploy Documentation

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx furo sphinx-autodoc-typehints myst-parser \
            nbsphinx sphinxcontrib-mermaid sphinx-autoapi sphinx-copybutton

      - name: Build HTML
        run: sphinx-build -b html docs/sources docs/sources/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sources/_build/html
          force_orphan: true
