name: Deploy Documentation

on:
  push:
    branches: [main, master]

permissions:
  contents: write   # needed by peaceiris to push to gh-pages

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install "docutils==0.20.1" sphinx furo sphinx-autodoc-typehints myst-parser nbsphinx sphinxcontrib-mermaid sphinx-autoapi sphinx-copybutton pytest pytest-cov "genbadge[coverage]"

      # Best-effort coverage so we can publish a badge even if docs fail
      - name: Run tests & collect coverage (best effort)
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=term --cov-report=xml:coverage.xml || true

      - name: Generate coverage.svg
        run: |
          if [ -f coverage.xml ]; then
            genbadge coverage -i coverage.xml -o coverage.svg
          else
            printf '%s' '<svg xmlns="http://www.w3.org/2000/svg" width="110" height="20"><rect width="110" height="20" fill="#555"/><rect x="60" width="50" height="20" fill="#9f9f9f"/><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="30" y="14">coverage</text><text x="85" y="14">N/A</text></g></svg>' > coverage.svg
          fi

      - name: Build HTML (non-fatal)
        run: |
          sphinx-build -b html docs/sources docs/sources/_build/html || true

      - name: Prepare site and copy badge
        run: |
          mkdir -p docs/sources/_build/html/_assets
          if [ ! -f docs/sources/_build/html/index.html ]; then
            printf '%s\n' '<!doctype html><meta charset="utf-8"><title>unifile_extractor docs</title><h1>Documentation</h1><p>If the Sphinx build failed this run, a minimal page is shown. The coverage badge is below.</p><p><img src="_assets/coverage.svg" alt="coverage badge"></p>' > docs/sources/_build/html/index.html
          fi
          cp coverage.svg docs/sources/_build/html/_assets/coverage.svg || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sources/_build/html
          force_orphan: true   # keeps gh-pages history clean
          # cname: your.custom.domain  # optional
